import 'package:flutter/material.dart';

import '../../theme/app_theme.dart';
import 'pustaka_models.dart';

final List<BookModel> pustakaDummyBooks = [
  BookModel(
    id: 'local-1',
    title: 'Hukum Fikih terhadap Uang Kertas (Uang Negara)',
    titleReadable: 'Hukum Fikih terhadap Uang Kertas (Uang Negara)',
    titleOriginal: 'Ahkam Fikih Uqud Al-Nuqud Al-Waraqiyyah',
    author: '-',
    language: 'ARAB',
    category: 'Fikih Muamalah',
    pages: 140,
    description:
        'Kajian fikih tentang status hukum uang kertas (uang negara) menurut perspektif syariah.',
    color: const Color(0xFF8B5CF6),
    isPremium: true,
    isLocal: true,
    pdfUrl:
        'https://drive.google.com/uc?export=download&id=1r0pw69ZF1kIyesBPeQRjoWy7o4kM9eI-',
  ),
  BookModel(
    id: 'local-2',
    title: 'Hukum-Hukum Fikih Terkait Mata Uang Elektronik',
    titleReadable: 'Hukum-Hukum Fikih Terkait Mata Uang Elektronik',
    titleOriginal: 'Al-Ahkam Al-Fikihiyyah Al-Mutaalliqah bil-Umulat',
    author: '-',
    language: 'ARAB',
    category: 'Fikih Muamalah',
    pages: 160,
    description:
        'Pembahasan tentang hukum fikih mata uang elektronik dan aset kripto.',
    color: MuamalahColors.primaryEmerald,
    isPremium: true,
    isLocal: true,
    pdfUrl:
        'https://drive.google.com/uc?export=download&id=1UUdluf4gXY3R04tXLwUXX8qU0nYTZRsx',
  ),
  BookModel(
    id: 'local-3',
    title: 'Fikih Muamalah Maliyah',
    titleReadable: 'Fikih Muamalah Maliyah',
    author: 'Dr. Wahbah Az-Zuhaili',
    language: 'ARAB',
    category: 'Fikih Muamalah',
    pages: 450,
    description:
        'Kitab komprehensif tentang hukum transaksi keuangan dalam Islam.',
    color: const Color(0xFF6366F1),
    isLocal: true,
  ),
  BookModel(
    id: 'local-4',
    title: 'Aset Kripto dalam Perspektif Syariah',
    titleReadable: 'Aset Kripto dalam Perspektif Syariah',
    author: 'Dr. Ahmad Ifham Sholihin',
    language: 'INDONESIA',
    category: 'Kripto Syariah',
    pages: 280,
    description:
        'Analisis komprehensif tentang status hukum aset kripto menurut fikih.',
    color: MuamalahColors.bitcoin,
    isLocal: true,
  ),
  BookModel(
    id: 'local-5',
    title: 'Hukum Uang dan Mata Uang Digital',
    titleReadable: 'Hukum Uang dan Mata Uang Digital',
    author: 'Dr. Ali Muhyiddin Al-Qaradaghi',
    language: 'ARAB',
    category: 'Kripto Syariah',
    pages: 180,
    description: 'Kajian fikih tentang mata uang digital dan akad muamalah.',
    color: MuamalahColors.ethereum,
    isLocal: true,
  ),
  BookModel(
    id: 'local-6',
    title: 'Ekonomi Islam: Teori dan Praktik',
    titleReadable: 'Ekonomi Islam: Teori dan Praktik',
    author: 'Prof. M. Umer Chapra',
    language: 'TERJEMAHAN',
    category: 'Ekonomi Islam',
    pages: 420,
    description:
        'Prinsip-prinsip ekonomi Islam dan penerapannya di era modern.',
    color: const Color(0xFF6366F1),
    isLocal: true,
  ),
  BookModel(
    id: 'local-7',
    title: 'Zakat Aset Digital dan Kripto',
    titleReadable: 'Zakat Aset Digital dan Kripto',
    author: 'Lembaga Amil Zakat Nasional',
    language: 'INDONESIA',
    category: 'Kripto Syariah',
    pages: 120,
    description:
        'Panduan praktis menghitung dan menunaikan zakat atas aset digital.',
    color: MuamalahColors.halal,
    isLocal: true,
  ),
  BookModel(
    id: 'local-8',
    title: 'Riba dan Transaksi Perbankan',
    titleReadable: 'Riba dan Transaksi Perbankan',
    author: 'Syekh Yusuf Al-Qaradawi',
    language: 'ARAB',
    category: 'Fikih Muamalah',
    pages: 350,
    description: 'Pembahasan detail tentang riba dan alternatif perbankan.',
    color: MuamalahColors.haram,
    isLocal: true,
  ),
  BookModel(
    id: 'local-9',
    title: 'Rantai Blok dan Kepatuhan Syariah',
    titleReadable: 'Rantai Blok dan Kepatuhan Syariah',
    author: 'Dr. Farrukh Habib',
    language: 'TERJEMAHAN',
    category: 'Kripto Syariah',
    pages: 200,
    description:
        'Eksplorasi rantai blok dari sudut pandang kepatuhan syariah.',
    color: const Color(0xFF14B8A6),
    isLocal: true,
  ),
  BookModel(
    id: 'local-10',
    title: 'Fikih Perdagangan Modern',
    titleReadable: 'Fikih Perdagangan Modern',
    author: 'Ustadz Dr. Oni Sahroni, MA',
    language: 'INDONESIA',
    category: 'Fikih Muamalah',
    pages: 250,
    description:
        'Panduan lengkap hukum perdagangan saham, valas, dan kripto.',
    color: const Color(0xFFEC4899),
    isLocal: true,
  ),
  BookModel(
    id: 'local-11',
    title: 'Kaidah Fikih Keuangan',
    titleReadable: 'Kaidah Fikih Keuangan',
    author: 'Dr. Nazih Hammad',
    language: 'ARAB',
    category: 'Referensi Ulama',
    pages: 280,
    description:
        'Kumpulan kaidah fiqhiyah terkait transaksi keuangan dan muamalah.',
    color: MuamalahColors.proses,
    isLocal: true,
  ),
];
